from automation.core.context_agent import ContextAgent

import os
from datetime import datetime


class CADGeneratorAgent(ContextAgent):

    name = "cad_generator_agent"


    def run(self, context):

        print("\nCAD Generator Agent:")


        geometry = context.get(
            "geometry_report",
            {}
        )


        task = context.get(
            "task",
            ""
        )


        filename = (
            "backend/app/cad_engine/generated/"
            "parametric_part.py"
        )


        os.makedirs(
            os.path.dirname(filename),
            exist_ok=True
        )


        code = f'''
"""
Generated by MyEngineer CAD Generator

Task:
{task}

Created:
{datetime.now()}
"""


class ParametricPart:


    def __init__(
        self,
        width=100,
        height=50,
        depth=20
    ):

        self.width = width
        self.height = height
        self.depth = depth



    def volume(self):

        return (
            self.width *
            self.height *
            self.depth
        )



    def validate(self):

        return (
            self.width > 0
            and
            self.height > 0
            and
            self.depth > 0
        )



def generate():

    return ParametricPart()
'''


        with open(
            filename,
            "w"
        ) as f:

            f.write(code)


        context["cad_generated"] = {

            "file": filename,

            "status": "created"

        }


        print(
            "Generated CAD module:",
            filename
        )


        return context
