"""
Generated by MyEngineer CoderAgent

CAD geometry validation module
"""


class GeometryValidator:


    name = "geometry_validator"


    def validate(self, solid):

        if solid is None:
            return {
                "valid": False,
                "reason": "Empty geometry"
            }


        return {
            "valid": True,
            "reason": "Geometry accepted"
        }
