import os
from datetime import datetime


class CoderAgent:

    name = "coder_agent"


    def run(self, context):

        generated = []

        task = context.get(
            "task",
            "cad"
        )


        filename = (
            "automation/generated/"
            "generated_design_report.py"
        )


        content = f'''
# Auto generated by MyEngineer Coder Agent

from datetime import datetime


class GeneratedDesign:

    name = "{task}"

    created = "{datetime.utcnow()}"


    def info(self):

        return {{
            "task": self.name,
            "created": self.created
        }}
'''


        os.makedirs(
            os.path.dirname(filename),
            exist_ok=True
        )


        with open(
            filename,
            "w"
        ) as file:

            file.write(content)


        generated.append(
            filename
        )


        context["code_generation"] = {

            "files_created": generated,

            "status": "SUCCESS"

        }


        print(
            "Coder Agent:",
            generated
        )


        return context
