import os


class CoderAgent:

    name = "coder_agent"


    def run(self, context):

        created = []

        cad_report = context.get(
            "cad_engineer",
            {}
        )


        recommendations = cad_report.get(
            "recommendations",
            []
        )


        target = "backend/app/cad_engine/geometry"

        os.makedirs(
            target,
            exist_ok=True
        )


        filename = os.path.join(
            target,
            "geometry_validator.py"
        )


        if not os.path.exists(filename):

            with open(
                filename,
                "w"
            ) as f:

                f.write(
'''"""
Generated by MyEngineer CoderAgent

CAD geometry validation module
"""


class GeometryValidator:


    name = "geometry_validator"


    def validate(self, solid):

        if solid is None:
            return {
                "valid": False,
                "reason": "Empty geometry"
            }


        return {
            "valid": True,
            "reason": "Geometry accepted"
        }
'''
                )


            created.append(filename)


        context["code_changes"] = {
            "created_files": created,
            "recommendations": recommendations
        }


        print("\nCoder Agent:")
        print(
            f"Created files: {len(created)}"
        )


        return context
